# NumPy – Core Concepts, Basics, and Essential Methods

**Goal of this tutorial**

- Understand what NumPy is and why it's important for data science & ML.
- Learn how to create and inspect NumPy arrays (`ndarray`).
- Practice indexing, slicing, reshaping, and combining arrays.
- Use essential mathematical operations, broadcasting, and statistics.
- Get comfortable with the random module and basic linear algebra.

## 1. What is NumPy and Why Use It?

**NumPy** (Numerical Python) is the fundamental package for numerical computing in Python.

Key features:
- Provides the **`ndarray`**: a fast, multidimensional array object.
- Supports **vectorized operations** (no explicit Python loops).
- Efficient **linear algebra, statistics, and random sampling**.
- Foundation for libraries like **pandas, SciPy, scikit-learn, PyTorch (conceptually), etc.**

Why not just use Python lists?
- Lists are **slow** for numerical work and **don't support vectorized math**.
- NumPy arrays store data in **contiguous memory**, enabling fast operations in C/Fortran under the hood.
- Arrays have a **fixed data type** (e.g., all `float64`), making them more efficient.


In [1]:
# Always import numpy as np (this is the standard convention)
import numpy as np

np.__version__

'2.3.5'

### Python List vs NumPy Array

Let's see a quick comparison to motivate why NumPy is useful.

In [2]:
import time

# Python list
lst = list(range(1_000_000))

start = time.time()
lst_squared = [x**2 for x in lst]
end = time.time()
print(f"Python list comprehension time: {end - start:.4f} seconds")

# NumPy array
arr = np.arange(1_000_000)

start = time.time()
arr_squared = arr**2  # vectorized operation
end = time.time()
print(f"NumPy array operation time: {end - start:.4f} seconds")

Python list comprehension time: 0.1123 seconds
NumPy array operation time: 0.0030 seconds


**Observation:** NumPy operations are typically **much faster** and the code is more concise and expressive.

## 2. Creating NumPy Arrays (`ndarray`)

There are multiple ways to create arrays in NumPy. The most common are:

1. From Python lists or tuples
2. Using built-in array creation functions (`arange`, `linspace`, `zeros`, `ones`, etc.)
3. Using random number generators


### 2.1 From Python Lists
Use `np.array()` to convert a list into a NumPy array.

In [3]:
# 1D array from list
a = np.array([1, 2, 3, 4])
print("a:", a)
print("type(a):", type(a))

# 2D array (matrix) from nested list
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nb:\n", b)
print("shape of b:", b.shape)

a: [1 2 3 4]
type(a): <class 'numpy.ndarray'>

b:
 [[1 2 3]
 [4 5 6]]
shape of b: (2, 3)


### 2.2 Important Array Attributes

Every `ndarray` has some important attributes:
- `ndim`: number of dimensions (axes)
- `shape`: size of each dimension (tuple)
- `size`: total number of elements
- `dtype`: data type of elements
- `itemsize`: size (in bytes) of each element
- `nbytes`: total bytes consumed by the elements


In [4]:
print("a =", a)
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)
print("itemsize:", a.itemsize)
print("nbytes:", a.nbytes)

print("\nb =\n", b)
print("ndim:", b.ndim)
print("shape:", b.shape)

a = [1 2 3 4]
ndim: 1
shape: (4,)
size: 4
dtype: int64
itemsize: 8
nbytes: 32

b =
 [[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)


### 2.3 Array Creation Functions

NumPy has many convenient functions to create arrays quickly:

- `np.arange(start, stop, step)`: like Python `range`, but returns an array.
- `np.linspace(start, stop, num)`: evenly spaced numbers between start and stop.
- `np.zeros(shape)`: array of zeros.
- `np.ones(shape)`: array of ones.
- `np.full(shape, fill_value)`: array filled with a specific value.
- `np.eye(n)`: identity matrix.


In [5]:
print("np.arange(0, 10):", np.arange(0, 10))
print("np.arange(0, 10, 2):", np.arange(0, 10, 2))

print("\nnp.linspace(0, 1, 5):", np.linspace(0, 1, 5))

print("\nnp.zeros((2, 3)):\n", np.zeros((2, 3)))
print("\nnp.ones((2, 3)):\n", np.ones((2, 3)))
print("\nnp.full((2, 3), 7):\n", np.full((2, 3), 7))
print("\nnp.eye(3):\n", np.eye(3))

np.arange(0, 10): [0 1 2 3 4 5 6 7 8 9]
np.arange(0, 10, 2): [0 2 4 6 8]

np.linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

np.zeros((2, 3)):
 [[0. 0. 0.]
 [0. 0. 0.]]

np.ones((2, 3)):
 [[1. 1. 1.]
 [1. 1. 1.]]

np.full((2, 3), 7):
 [[7 7 7]
 [7 7 7]]

np.eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2.4 Data Types (`dtype`)

NumPy has many data types: `int32`, `int64`, `float32`, `float64`, `bool`, etc.

By default, NumPy chooses a data type based on the input, but you can override it with the `dtype` argument.

In [6]:
arr_int = np.array([1, 2, 3])
arr_float = np.array([1, 2, 3], dtype=np.float64)
arr_bool = np.array([0, 1, 2], dtype=bool)

print("arr_int:", arr_int, "dtype:", arr_int.dtype)
print("arr_float:", arr_float, "dtype:", arr_float.dtype)
print("arr_bool:", arr_bool, "dtype:", arr_bool.dtype)

arr_int: [1 2 3] dtype: int64
arr_float: [1. 2. 3.] dtype: float64
arr_bool: [False  True  True] dtype: bool


## 3. Indexing and Slicing

Indexing and slicing work similarly to Python lists but are more powerful, especially for multi-dimensional arrays.

Important ideas:
- Indices are **0-based**: first element is index `0`.
- Use `:` for slices (`start:stop:step`).
- For 2D arrays: `array[row_index, column_index]`.


### 3.1 Basic Indexing – 1D


In [7]:
arr = np.array([10, 20, 30, 40, 50])
print("arr:", arr)

print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing: arr[start:stop] (stop is excluded)
print("arr[1:4] (index 1 to 3):", arr[1:4])
print("arr[:3] (start to index 2):", arr[:3])
print("arr[2:] (index 2 to end):", arr[2:])
print("arr[::2] (step of 2):", arr[::2])

arr: [10 20 30 40 50]
First element: 10
Last element: 50
arr[1:4] (index 1 to 3): [20 30 40]
arr[:3] (start to index 2): [10 20 30]
arr[2:] (index 2 to end): [30 40 50]
arr[::2] (step of 2): [10 30 50]


### 3.2 Indexing and Slicing – 2D


In [8]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("matrix =\n", matrix)

# Access single element: matrix[row, column]
print("Element at row 0, col 1:", matrix[0, 1])  # 2
print("Element at row 2, col 2:", matrix[2, 2])  # 9

# Row slicing
print("\nFirst row:", matrix[0, :])
print("Second column:", matrix[:, 1])

# Sub-matrix
print("\nTop-left 2x2 block:\n", matrix[0:2, 0:2])

matrix =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, col 1: 2
Element at row 2, col 2: 9

First row: [1 2 3]
Second column: [2 5 8]

Top-left 2x2 block:
 [[1 2]
 [4 5]]


### 3.3 Views vs Copies (Important!)

By default, slicing a NumPy array **returns a view** (not a copy). This means:
- Both the original array and the slice **share the same data in memory**.
- Modifying the slice will **also modify** the original array.

To create an actual copy, use `.copy()`.

In [9]:
arr = np.array([1, 2, 3, 4, 5])
slice_view = arr[1:4]  # view

print("Original arr:", arr)
print("slice_view:", slice_view)

# Modify slice
slice_view[0] = 99
print("\nAfter modifying slice_view[0] = 99")
print("arr:", arr)          # arr changed!
print("slice_view:", slice_view)

# To avoid this, use copy()
arr2 = np.array([1, 2, 3, 4, 5])
slice_copy = arr2[1:4].copy()
slice_copy[0] = 99

print("\nUsing copy()")
print("arr2:", arr2)         # unchanged
print("slice_copy:", slice_copy)

Original arr: [1 2 3 4 5]
slice_view: [2 3 4]

After modifying slice_view[0] = 99
arr: [ 1 99  3  4  5]
slice_view: [99  3  4]

Using copy()
arr2: [1 2 3 4 5]
slice_copy: [99  3  4]


## 4. Fancy Indexing and Boolean Masking

Beyond basic slices, NumPy allows **fancy indexing** using integer arrays/lists and **boolean masks**.

These are extremely powerful for filtering and selecting specific elements.

### 4.1 Fancy Indexing with Integer Arrays


In [10]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]

print("arr:", arr)
print("indices:", indices)
print("arr[indices]:", arr[indices])

matrix = np.arange(1, 13).reshape(3, 4)
print("\nmatrix =\n", matrix)

row_indices = [0, 1, 2]
col_indices = [1, 2, 3]
print("\nSelected elements:", matrix[row_indices, col_indices])
# Explanation: picks (0,1), (1,2), (2,3)

arr: [10 20 30 40 50]
indices: [0, 2, 4]
arr[indices]: [10 30 50]

matrix =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Selected elements: [ 2  7 12]


### 4.2 Boolean Masking

A **boolean mask** is an array of True/False values used to filter elements.

Steps:
1. Create a boolean condition (e.g., `arr > 0`).
2. Use it inside the index: `arr[condition]`.


In [11]:
arr = np.array([-3, -1, 0, 2, 4, 6])

mask = arr > 0
print("arr:", arr)
print("mask:", mask)
print("Positive values:", arr[mask])

# Combine conditions using & (and), | (or)
between_0_and_5 = (arr >= 0) & (arr <= 5)
print("\nValues between 0 and 5:", arr[between_0_and_5])

arr: [-3 -1  0  2  4  6]
mask: [False False False  True  True  True]
Positive values: [2 4 6]

Values between 0 and 5: [0 2 4]


## 5. Reshaping and Shape Manipulation

NumPy makes it easy to change the **shape** (dimensions) of an array without changing the underlying data.

### 5.1 `reshape` and `ravel` / `flatten`


In [12]:
arr = np.arange(12)
print("arr:", arr)

# Reshape to 3x4
matrix = arr.reshape(3, 4)
print("\nReshaped to 3x4:\n", matrix)

# Reshape to 2x2x3
tensor = arr.reshape(2, 2, 3)
print("\nReshaped to 2x2x3:\n", tensor)

# Flatten back to 1D
print("\nravel (view if possible):", matrix.ravel())
print("flatten (always copy):", matrix.flatten())

arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to 2x2x3:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

ravel (view if possible): [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten (always copy): [ 0  1  2  3  4  5  6  7  8  9 10 11]


**Note:**
- `reshape` tries to return a **view** when possible (no data copy).
- `ravel` is similar: returns a flattened view when possible.
- `flatten` **always** returns a copy.


### 5.2 Transpose and Axes


In [13]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("matrix =\n", matrix)
print("\nTransposed (matrix.T) =\n", matrix.T)

# For higher dimensions, use np.transpose with axes
tensor = np.arange(24).reshape(2, 3, 4)
print("\ntensor shape:", tensor.shape)
tensor_T = np.transpose(tensor, (0, 2, 1))  # swap axes 1 and 2
print("Transposed tensor shape:", tensor_T.shape)

matrix =
 [[1 2 3]
 [4 5 6]]

Transposed (matrix.T) =
 [[1 4]
 [2 5]
 [3 6]]

tensor shape: (2, 3, 4)
Transposed tensor shape: (2, 4, 3)


### 5.3 Adding and Removing Dimensions

Sometimes we want to increase or decrease the number of dimensions.

- Use `np.newaxis` or `None` to add a dimension.
- Use `np.expand_dims` / `np.squeeze` for more control.


In [14]:
arr = np.array([1, 2, 3])
print("arr:", arr)
print("shape:", arr.shape)

# Add a new axis to make it a column vector (3x1)
col = arr[:, np.newaxis]
print("\nColumn vector:\n", col)
print("shape:", col.shape)

# Add a new axis to make it a row vector (1x3)
row = arr[np.newaxis, :]
print("\nRow vector:", row)
print("shape:", row.shape)

# Using expand_dims
expanded = np.expand_dims(arr, axis=0)  # same as arr[np.newaxis, :]
print("\nUsing expand_dims (axis=0): shape =", expanded.shape)

# Squeeze to remove dimensions of size 1
sq = np.squeeze(expanded)
print("Squeezed shape:", sq.shape)

arr: [1 2 3]
shape: (3,)

Column vector:
 [[1]
 [2]
 [3]]
shape: (3, 1)

Row vector: [[1 2 3]]
shape: (1, 3)

Using expand_dims (axis=0): shape = (1, 3)
Squeezed shape: (3,)


## 6. Combining and Splitting Arrays

NumPy provides multiple ways to **concatenate** (join) and **split** arrays.


### 6.1 Concatenation, Stacking


In [15]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print("a =\n", a)
print("b =\n", b)

# Concatenate along rows (axis=0)
print("\nnp.concatenate([a, b], axis=0):\n", np.concatenate([a, b], axis=0))

# Concatenate along columns (axis=1)
print("\nnp.concatenate([a, b], axis=1):\n", np.concatenate([a, b], axis=1))

# vstack / hstack helpers
print("\nnp.vstack([a, b]):\n", np.vstack([a, b]))
print("\nnp.hstack([a, b]):\n", np.hstack([a, b]))

# stack adds a new axis
stacked = np.stack([a, b], axis=0)
print("\nnp.stack([a, b], axis=0): shape =", stacked.shape)

a =
 [[1 2]
 [3 4]]
b =
 [[5 6]
 [7 8]]

np.concatenate([a, b], axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.concatenate([a, b], axis=1):
 [[1 2 5 6]
 [3 4 7 8]]

np.vstack([a, b]):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

np.hstack([a, b]):
 [[1 2 5 6]
 [3 4 7 8]]

np.stack([a, b], axis=0): shape = (2, 2, 2)


### 6.2 Splitting


In [16]:
c = np.arange(10)
print("c:", c)

left, right = np.split(c, 2)
print("\nSplit into 2 equal parts:")
print("left:", left)
print("right:", right)

# For 2D arrays
matrix = np.arange(16).reshape(4, 4)
print("\nmatrix =\n", matrix)

upper, lower = np.vsplit(matrix, 2)
print("\nUpper:\n", upper)
print("Lower:\n", lower)

left, right = np.hsplit(matrix, 2)
print("\nLeft:\n", left)
print("Right:\n", right)

c: [0 1 2 3 4 5 6 7 8 9]

Split into 2 equal parts:
left: [0 1 2 3 4]
right: [5 6 7 8 9]

matrix =
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Upper:
 [[0 1 2 3]
 [4 5 6 7]]
Lower:
 [[ 8  9 10 11]
 [12 13 14 15]]

Left:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 7. Elementwise Operations and Universal Functions (ufuncs)

NumPy supports **elementwise** arithmetic and mathematical functions.

Examples:
- Arithmetic: `+`, `-`, `*`, `/`, `//`, `**`, `%`
- Comparisons: `<`, `>`, `==`, `!=`
- Math functions: `np.sqrt`, `np.exp`, `np.log`, `np.sin`, `np.cos`, ...


In [17]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print("a:", a)
print("b:", b)

print("\na + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("b / a:", b / a)
print("a ** 2:", a ** 2)

# Comparison
print("\na < 3:", a < 3)
print("b == 20:", b == 20)

# Mathematical functions
x = np.linspace(0, np.pi, 5)
print("\nx:", x)
print("sin(x):", np.sin(x))
print("sqrt(x):", np.sqrt(x))

a: [1 2 3]
b: [10 20 30]

a + b: [11 22 33]
a - b: [ -9 -18 -27]
a * b: [10 40 90]
b / a: [10. 10. 10.]
a ** 2: [1 4 9]

a < 3: [ True  True False]
b == 20: [False  True False]

x: [0.         0.78539816 1.57079633 2.35619449 3.14159265]
sin(x): [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
sqrt(x): [0.         0.88622693 1.25331414 1.53499006 1.77245385]


**Universal functions (ufuncs)** are functions that operate elementwise on arrays. They are highly optimized and support broadcasting.


## 8. Aggregation and Statistics

Common aggregation functions:
- `np.sum`, `np.mean`, `np.std`, `np.var`
- `np.min`, `np.max`, `np.argmin`, `np.argmax`
- `np.median`

They can operate on the **whole array** or along a specific **axis**.

In [18]:
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

print("data =\n", data)

print("\nTotal sum:", data.sum())
print("Mean:", data.mean())
print("Standard deviation:", data.std())
print("Min:", data.min(), "Max:", data.max())
print("Index of min:", data.argmin(), "Index of max:", data.argmax())

# Along axes
print("\nColumn-wise sum (axis=0):", data.sum(axis=0))
print("Row-wise sum (axis=1):", data.sum(axis=1))

data =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Total sum: 45
Mean: 5.0
Standard deviation: 2.581988897471611
Min: 1 Max: 9
Index of min: 0 Index of max: 8

Column-wise sum (axis=0): [12 15 18]
Row-wise sum (axis=1): [ 6 15 24]


## 9. Broadcasting

**Broadcasting** is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.

Rules (simplified):
1. If the arrays differ in their number of dimensions, prepend 1s to the smaller shape.
2. Two dimensions are compatible if they are equal or one of them is 1.
3. If they are compatible along all dimensions, NumPy *stretches* the array with dimension 1 to match the other.


In [19]:
# Example 1: add scalar to array
a = np.array([1, 2, 3])
print("a:", a)
print("a + 10:", a + 10)

# Example 2: (3,) with (3,3)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\nmatrix =\n", matrix)
print("\nmatrix + a:\n", matrix + a)  # a broadcasts to each row

# Example 3: column vector with row vector
col = np.array([[1], [2], [3]])  # shape (3,1)
row = np.array([10, 20, 30])     # shape (3,)
print("\ncol shape:", col.shape)
print("row shape:", row.shape)
print("\ncol + row =\n", col + row)

a: [1 2 3]
a + 10: [11 12 13]

matrix =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

matrix + a:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

col shape: (3, 1)
row shape: (3,)

col + row =
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


Try to manually compute shapes and show students how NumPy matches dimensions step by step.

## 10. Basic Linear Algebra Operations

NumPy includes many **linear algebra** routines in `np.linalg`:

- Matrix multiplication: `@` or `np.matmul`
- Dot product: `np.dot`
- Transpose: `.T`
- Inverse: `np.linalg.inv`
- Solve linear system: `np.linalg.solve`


In [20]:
A = np.array([[1, 2],
              [3, 4]])
b = np.array([5, 6])

print("A =\n", A)
print("b =", b)

# Matrix multiplication
print("\nA @ b:", A @ b)
print("np.matmul(A, b):", np.matmul(A, b))

# Inverse of A
A_inv = np.linalg.inv(A)
print("\nInverse of A:\n", A_inv)
print("A @ A_inv (should be identity):\n", A @ A_inv)

# Solve Ax = b
x = np.linalg.solve(A, b)
print("\nSolution of Ax = b:", x)

A =
 [[1 2]
 [3 4]]
b = [5 6]

A @ b: [17 39]
np.matmul(A, b): [17 39]

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A @ A_inv (should be identity):
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Solution of Ax = b: [-4.   4.5]


## 11. Random Numbers

NumPy has a powerful random module. In newer versions, it's recommended to use the **`Generator`** API.

Steps:
1. Create a generator with `np.random.default_rng(seed)`.
2. Use methods like `integers`, `normal`, `uniform`, `choice`, etc.


In [21]:
rng = np.random.default_rng(seed=42)

print("Random integers 0-9:", rng.integers(0, 10, size=5))
print("\nRandom samples from standard normal:", rng.normal(size=5))
print("\nRandom choice from array:", rng.choice(["apple", "banana", "cherry"], size=3))

Random integers 0-9: [0 7 6 4 4]

Random samples from standard normal: [ 0.94056472 -1.95103519 -1.30217951  0.1278404  -0.31624259]

Random choice from array: ['cherry' 'banana' 'apple']


## 12. Common Pitfalls and Best Practices

1. **Mixing Python lists and NumPy arrays**
   - Prefer doing math with arrays only: `np.array([...])`, not raw lists.

2. **Views vs Copies**
   - Remember: slices are usually **views**; use `.copy()` when you need independent data.

3. **Integer division vs float division**
   - In NumPy, `/` always returns float (for numeric arrays), `//` is floor division.

4. **Data types**
   - Be careful when mixing `int` and `float` arrays, or `int` and `bool`. Use `dtype` explicitly when needed.

5. **Using vectorization instead of loops**
   - Try to **avoid Python `for` loops** over array elements. Use vectorized operations and broadcasting.


## 13. Mini-Exercises (For Students)

Try these without looking at the solutions. Then compare with the example solutions below.

1. Create a 1D NumPy array of integers from 10 to 20 (inclusive). Extract the even numbers using boolean masking.
2. Create a 3x3 identity matrix using NumPy. Multiply it with a random 3x3 matrix and observe the result.
3. Given a 2D array, compute the **mean of each column** and **mean of each row**.
4. Use broadcasting to add a 1D array of shape `(3,)` to a 2D array of shape `(4, 3)`.
5. Generate 1000 random numbers from a normal distribution and compute their mean and standard deviation.


### Example Solutions (Run after trying yourself)


In [22]:
# 1. Even numbers between 10 and 20
arr = np.arange(10, 21)
even = arr[arr % 2 == 0]
print("1) Even numbers:", even)

# 2. Identity matrix and random matrix
I = np.eye(3)
rng = np.random.default_rng(0)
M = rng.integers(0, 10, size=(3, 3))

print("\n2) I =\n", I)
print("M =\n", M)
print("I @ M =\n", I @ M)  # should be same as M

# 3. Column-wise and row-wise mean
data = np.arange(1, 10).reshape(3, 3)
print("\n3) data =\n", data)
print("Column-wise mean:", data.mean(axis=0))
print("Row-wise mean:", data.mean(axis=1))

# 4. Broadcasting example
A = np.arange(12).reshape(4, 3)
b = np.array([10, 20, 30])
print("\n4) A =\n", A)
print("b =", b)
print("A + b =\n", A + b)

# 5. Random normal distribution
samples = rng.normal(loc=0, scale=1, size=1000)
print("\n5) Mean:", samples.mean())
print("Standard deviation:", samples.std())

1) Even numbers: [10 12 14 16 18 20]

2) I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
M =
 [[8 6 5]
 [2 3 0]
 [0 0 1]]
I @ M =
 [[8. 6. 5.]
 [2. 3. 0.]
 [0. 0. 1.]]

3) data =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Column-wise mean: [4. 5. 6.]
Row-wise mean: [2. 5. 8.]

4) A =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
b = [10 20 30]
A + b =
 [[10 21 32]
 [13 24 35]
 [16 27 38]
 [19 30 41]]

5) Mean: -0.047651986836261206
Standard deviation: 0.9781661101001475
